services:
  localsite-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - BODY_SIZE_LIMIT=1M
      # Choose the default provider (ollama or lm_studio)
      - DEFAULT_PROVIDER=ollama
    # volumes:
    #   - ./:/app
    extra_hosts:
      # Important: Allows access to the host machine
      - "host.docker.internal:host-gateway"
